#!/bin/bash
# Installs KiCad 10 (kicad-cli + pcbnew Python + symbol/footprint libraries) in
# a Claude Code cloud container so the hardware/kicad/ generator pipeline works
# there. Mirrors the layer in .devcontainer/Dockerfile so a cloud session and a
# local dev container regenerate byte-identical boards.
#
# Ubuntu's own repository ships KiCad 7, which the generator no longer supports
# (hardware/kicad/README.md), so the official PPA is the only source. Like the
# ESP-IDF installer, this checks reachability up front and reports what to allow
# rather than working around a block: a board regenerated by a different KiCad
# than the one the design was authored against is not a usable artifact.
#
# The 3D model pack (kicad-packages3d) is installed too: without it
# `make pcb-render` still exits 0 but draws only the handful of models vendored
# in hardware/kicad/3dmodels/, and every resistor, IC and terminal block comes
# out as bare pads — a render that must never be committed, from a command that
# reports success. Measured on this image it is a 424 MB download and 3.2 GB on
# disk, ~40 s. KICAD_3D=0 skips it when disk is tight and renders are not
# needed. (.devcontainer/Dockerfile keeps its own opt-in default: a local
# image is rebuilt rarely and its size is paid once, not every session.)
#
# Finally it exports KPY for the session — see the end of this file and
# .claude/hooks/kicad-python for why a bare `python3` is not usable here.
set -euo pipefail

PPA="kicad/kicad-10.0-releases"
PPA_URL="https://ppa.launchpadcontent.net/${PPA}/ubuntu"

HOOK_LIB="$(dirname "${BASH_SOURCE[0]}")/lib"
# shellcheck source=lib/preflight.sh
. "$HOOK_LIB/preflight.sh"
# shellcheck source=lib/toolchain.sh
. "$HOOK_LIB/toolchain.sh"

PREFIX='[kicad install]'
log() { printf '%s %s\n' "$PREFIX" "$*"; }

. /etc/os-release 2>/dev/null || true
CODENAME="${UBUNTU_CODENAME:-noble}"

# ── Migration: drop the unsigned source an older revision of this script
# wrote when the keyserver was blocked. ───────────────────────────────────
#
# That `[trusted=yes]` fallback is gone, but the file it left behind is not:
# any container that ever ran the old script still has apt configured to trust
# this PPA *without signature verification*. Two reasons this runs first, ahead
# of every exit below:
#
#   - Where the old fallback installed a working KiCad, the fast path returns
#     immediately, so a cleanup placed after it would never run on exactly the
#     containers that have the unsafe source. Same for a still-blocked policy,
#     which exits at the preflight.
#   - Once the properly signed entry for the same URI exists, apt refuses to
#     read either —
#       E: Conflicting values set for option Trusted regarding source …
#     which fails every apt-get in this script, not just the one that added it.
#
# Removing an unverified duplicate is worth doing whether or not we go on to
# install anything, so it is not conditional on what follows.
LEGACY_LIST=/etc/apt/sources.list.d/kicad.list
if [ -f "$LEGACY_LIST" ] && grep -q 'trusted=yes' "$LEGACY_LIST" &&
    grep -q 'ppa.launchpadcontent.net' "$LEGACY_LIST"; then
    log "removing legacy unsigned PPA entry ($LEGACY_LIST)"
    rm -f "$LEGACY_LIST"
fi

# ── Fast path: a usable KiCad is already present → nothing to do. ─────────
# Note this is a version+pcbnew check, not `command -v`: the Ubuntu archive
# ships a kicad-cli that is too old for the generator, and it is on PATH in the
# stock image.
#
# "Nothing to do" covers KiCad itself only. The session setup at the end —
# the 3D pack, Xvfb and the KPY export — still has to happen on a warm
# container, since CLAUDE_ENV_FILE is fresh for every session.
HOOKS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KICAD_3D="${KICAD_3D:-1}"
export DEBIAN_FRONTEND=noninteractive

# apt_install PKG... — quiet install, retried once after `apt-get update`.
# A fresh container's package index can be days older than the mirror, and an
# install that needs a since-superseded .deb 404s until the index is refreshed.
apt_install() {
    apt-get install -y -qq --no-install-recommends "$@" >/dev/null 2>&1 && return 0
    apt-get update -qq >/dev/null 2>&1 || true
    apt-get install -y -qq --no-install-recommends "$@" >/dev/null
}

session_setup() {
    # 3D models. dpkg-query rather than a directory probe: an interrupted
    # unpack leaves a partial 3dmodels/ that looks installed.
    if [ "$KICAD_3D" = "1" ]; then
        if ! dpkg-query -W -f='${Status}' kicad-packages3d 2>/dev/null |
            grep -q 'install ok installed'; then
            log "installing kicad-packages3d (3D models for pcb-render; ~40 s)…"
            apt_install kicad-packages3d ||
                log "kicad-packages3d install failed — pcb-render will omit most parts."
        fi
    fi

    # Xvfb, for the wx.App the generator starts. From the Ubuntu archive, so
    # it does not depend on the Launchpad hosts.
    if ! command -v Xvfb >/dev/null 2>&1; then
        log "installing xvfb (virtual display for the pcbnew scripts)…"
        apt_install xvfb ||
            log "xvfb install failed — kicad_build.py/check_placement.py will need a display."
    fi

    local kpy="$HOOKS_DIR/kicad-python" py
    py="$(toolchain_kicad_python)"
    if [ -n "${CLAUDE_ENV_FILE:-}" ]; then
        # Replace rather than append-if-absent: the interpreter can change
        # between sessions (a KiCad or image upgrade) and a stale value would
        # be preferred over the wrapper's own probe.
        sed -i '/^export KPY=/d; /^export BISQUE_KICAD_PY=/d' "$CLAUDE_ENV_FILE" 2>/dev/null || true
        printf 'export KPY=%q\nexport BISQUE_KICAD_PY=%q\n' "$kpy" "$py" >>"$CLAUDE_ENV_FILE"
    fi

    # Prove the whole path the generator takes, display included, rather than
    # reporting ready on the strength of an import.
    if BISQUE_KICAD_PY="$py" "$kpy" -c 'import pcbnew, wx; wx.App(False)' >/dev/null 2>&1; then
        log "KPY=$kpy (${py}, virtual display) — exported for this session."
    else
        log "WARNING: $kpy cannot start wx.App — pcbnew scripts that need it"
        log "(kicad_build.py, check_placement.py) will fail. See docs/cloud-dev.md."
    fi
    # The board path is spelled out on purpose. kicad_build.py defaults its
    # output to a bare "bisque-controller.kicad_pcb" resolved against the
    # current directory, so run from the repo root it writes a brand-new
    # top-level board and DRC report and leaves the tracked one untouched — a
    # regeneration that appears to work and changes nothing.
    log "regenerate the board with: make pcb-build   (or"
    log "  \$KPY hardware/kicad/generator/kicad_build.py hardware/kicad/bisque-controller.kicad_pcb)"
}

if toolchain_kicad_ready; then
    log "kicad-cli $(kicad-cli version 2>/dev/null) already installed (pcbnew OK)."
    session_setup
    exit 0
fi

# ── Preflight ─────────────────────────────────────────────────────────────
# Three distinct hosts, all required. The PPA serves the packages;
# add-apt-repository resolves the `ppa:` shorthand through launchpadlib, which
# talks to api.launchpad.net; and the keyserver serves the signing key the
# packages are verified against. Probing only the first two would let the
# preflight pass and then fail inside add-apt-repository — the previous
# version of this script fell back to `[trusted=yes]` when the keyserver was
# blocked, which installs unverified packages. Inside a sandbox that is
# survivable, but it is exactly the kind of quiet workaround that makes a
# container stop matching the environment it is supposed to reproduce.
if ! preflight_check "$PREFIX" \
    "ppa.launchpadcontent.net|http|${PPA_URL}/dists/${CODENAME}/InRelease|KiCad 10 packages" \
    "api.launchpad.net|http|https://api.launchpad.net/1.0/|PPA lookup by add-apt-repository (launchpadlib)" \
    "keyserver.ubuntu.com|http|https://keyserver.ubuntu.com/|PPA signing key (package verification)"; then
    preflight_report_blocked "$PREFIX" "the KiCad PCB pipeline"
    log "Everything else in hardware/kicad/ is source you can still edit; only"
    log "regenerating and rendering the board needs KiCad."
    exit 0
fi
log "PPA reachable — installing KiCad 10 for ${CODENAME}…"

apt-get install -y -qq software-properties-common >/dev/null

# add-apt-repository is `#!/usr/bin/python3` and imports apt_pkg, but this
# image's python3 alternative points at 3.11 while noble's python3-apt ships
# only the 3.12 ABI extension — so the stock invocation dies with
# ModuleNotFoundError before it ever reaches the network. Drive it with the
# interpreter that actually owns dist-packages instead. Reachability was
# already established above, so a failure here is a real one: let it stop the
# script rather than leaving a half-added PPA behind.
if ! APT_PY="$(toolchain_python_for apt_pkg)"; then
    log "ERROR: no system python3 can 'import apt_pkg', so add-apt-repository"
    log "cannot run. Expected python3-apt to provide it — see docs/cloud-dev.md."
    exit 1
fi
"$APT_PY" /usr/bin/add-apt-repository -y "ppa:${PPA}" >/dev/null
apt-get update -qq 2>/dev/null || true

log "installing kicad + symbol/footprint libraries (~1.5 GB)…"
apt-get install -y -qq --no-install-recommends kicad kicad-symbols kicad-footprints >/dev/null

# Verify with the same predicate the fast path and the session summary use, so
# a partially-working install is never reported as done.
if ! toolchain_kicad_ready; then
    log "ERROR: kicad installed but is not usable (needs major >= ${KICAD_MIN_MAJOR}"
    log "and a working 'import pcbnew') — see docs/cloud-dev.md."
    exit 1
fi

log "installed: $(kicad-cli version 2>/dev/null || echo '?') (pcbnew OK)"
session_setup
