#!/bin/bash
# Installs KiCad 10 (kicad-cli + pcbnew Python + symbol/footprint libraries) in
# a Claude Code cloud container so the hardware/kicad/ generator pipeline works
# there. Mirrors the layer in .devcontainer/Dockerfile so a cloud session and a
# local dev container regenerate byte-identical boards.
#
# Ubuntu's own repository ships KiCad 7, which the generator no longer supports
# (hardware/kicad/README.md), so the official PPA is the only source. Like the
# ESP-IDF installer, this checks reachability up front and reports what to allow
# rather than working around a block: a board regenerated by a different KiCad
# than the one the design was authored against is not a usable artifact.
#
# The 3D model pack (kicad-packages3d, ~6 GB) is skipped by default; set
# KICAD_3D=1 to install it (needed only for component models in
# `kicad-cli pcb render` — the board itself renders without it).
set -euo pipefail

PPA="kicad/kicad-10.0-releases"
PPA_URL="https://ppa.launchpadcontent.net/${PPA}/ubuntu"

HOOK_LIB="$(dirname "${BASH_SOURCE[0]}")/lib"
# shellcheck source=lib/preflight.sh
. "$HOOK_LIB/preflight.sh"
# shellcheck source=lib/toolchain.sh
. "$HOOK_LIB/toolchain.sh"

PREFIX='[kicad install]'
log() { printf '%s %s\n' "$PREFIX" "$*"; }

. /etc/os-release 2>/dev/null || true
CODENAME="${UBUNTU_CODENAME:-noble}"

# ── Fast path: a usable KiCad is already present → nothing to do. ─────────
# Note this is a version+pcbnew check, not `command -v`: the Ubuntu archive
# ships a kicad-cli that is too old for the generator, and it is on PATH in the
# stock image.
if toolchain_kicad_ready; then
    log "kicad-cli $(kicad-cli version 2>/dev/null) already installed (pcbnew OK)."
    exit 0
fi

# ── Preflight ─────────────────────────────────────────────────────────────
# Three distinct hosts, all required. The PPA serves the packages;
# add-apt-repository resolves the `ppa:` shorthand through launchpadlib, which
# talks to api.launchpad.net; and the keyserver serves the signing key the
# packages are verified against. Probing only the first two would let the
# preflight pass and then fail inside add-apt-repository — the previous
# version of this script fell back to `[trusted=yes]` when the keyserver was
# blocked, which installs unverified packages. Inside a sandbox that is
# survivable, but it is exactly the kind of quiet workaround that makes a
# container stop matching the environment it is supposed to reproduce.
if ! preflight_check "$PREFIX" \
    "ppa.launchpadcontent.net|http|${PPA_URL}/dists/${CODENAME}/InRelease|KiCad 10 packages" \
    "api.launchpad.net|http|https://api.launchpad.net/1.0/|PPA lookup by add-apt-repository (launchpadlib)" \
    "keyserver.ubuntu.com|http|https://keyserver.ubuntu.com/|PPA signing key (package verification)"; then
    preflight_report_blocked "$PREFIX" "the KiCad PCB pipeline"
    log "Everything else in hardware/kicad/ is source you can still edit; only"
    log "regenerating and rendering the board needs KiCad."
    exit 0
fi
log "PPA reachable — installing KiCad 10 for ${CODENAME}…"

export DEBIAN_FRONTEND=noninteractive

# Drop the unsigned source an older revision of this script wrote when the
# keyserver was blocked. That `[trusted=yes]` fallback is gone, but the file it
# left behind is not: any container that ever ran the old script still has apt
# configured to trust this PPA unverified, and once the properly signed entry
# for the same URI exists apt refuses to read either —
#   E: Conflicting values set for option Trusted regarding source …
# which fails every apt-get below, not just the one that added it. So this runs
# before the first apt call, not next to add-apt-repository. Removing it is
# also the point: an unsigned duplicate of a repo we are about to add signed
# has no reason to survive.
LEGACY_LIST=/etc/apt/sources.list.d/kicad.list
if [ -f "$LEGACY_LIST" ] && grep -q 'trusted=yes' "$LEGACY_LIST" &&
    grep -q 'ppa.launchpadcontent.net' "$LEGACY_LIST"; then
    log "removing legacy unsigned PPA entry ($LEGACY_LIST)"
    rm -f "$LEGACY_LIST"
fi

apt-get install -y -qq software-properties-common >/dev/null

# add-apt-repository is `#!/usr/bin/python3` and imports apt_pkg, but this
# image's python3 alternative points at 3.11 while noble's python3-apt ships
# only the 3.12 ABI extension — so the stock invocation dies with
# ModuleNotFoundError before it ever reaches the network. Drive it with the
# interpreter that actually owns dist-packages instead. Reachability was
# already established above, so a failure here is a real one: let it stop the
# script rather than leaving a half-added PPA behind.
if ! APT_PY="$(toolchain_python_for apt_pkg)"; then
    log "ERROR: no system python3 can 'import apt_pkg', so add-apt-repository"
    log "cannot run. Expected python3-apt to provide it — see docs/cloud-dev.md."
    exit 1
fi
"$APT_PY" /usr/bin/add-apt-repository -y "ppa:${PPA}" >/dev/null
apt-get update -qq 2>/dev/null || true

log "installing kicad + symbol/footprint libraries (~1.5 GB)…"
PKGS="kicad kicad-symbols kicad-footprints"
[ "${KICAD_3D:-0}" = "1" ] && PKGS="$PKGS kicad-packages3d"
# shellcheck disable=SC2086
apt-get install -y -qq --no-install-recommends $PKGS >/dev/null

# Verify with the same predicate the fast path and the session summary use, so
# a partially-working install is never reported as done.
if ! toolchain_kicad_ready; then
    log "ERROR: kicad installed but is not usable (needs major >= ${KICAD_MIN_MAJOR}"
    log "and a working 'import pcbnew') — see docs/cloud-dev.md."
    exit 1
fi

log "installed: $(kicad-cli version 2>/dev/null || echo '?') (pcbnew OK)"
# Advertise a command that actually runs. `python3` on PATH is the ESP-IDF
# venv once install-esp-idf.sh has activated — a 3.11 with no system
# site-packages, so it cannot import pcbnew however well KiCad is installed.
# (Same shape as the cmake/PATH collision: activating IDF shadows a system
# tool.) Test the PATH interpreter rather than assuming either way, and name
# the absolute one when it loses — the role the README's $KPY plays on macOS,
# where pcbnew lives in KiCad.app's bundled Python.
PCB_PY="$(toolchain_python_for pcbnew)"
if python3 -c "import pcbnew" >/dev/null 2>&1; then
    log "regenerate the board with hardware/kicad/generator/kicad_build.py"
else
    log "note: python3 on PATH ($(command -v python3)) cannot import pcbnew;"
    log "regenerate the board with:"
    log "  ${PCB_PY} hardware/kicad/generator/kicad_build.py"
fi
