#!/bin/bash
# Installs KiCad 10 (kicad-cli + pcbnew Python + symbol/footprint libraries) in
# a Claude Code cloud container so the hardware/kicad/ generator pipeline works
# there. Mirrors the layer in .devcontainer/Dockerfile so a cloud session and a
# local dev container regenerate byte-identical boards.
#
# Ubuntu's own repository ships KiCad 7, which the generator no longer supports
# (hardware/kicad/README.md), so the official PPA is the only source. Like the
# ESP-IDF installer, this checks reachability up front and reports what to allow
# rather than working around a block: a board regenerated by a different KiCad
# than the one the design was authored against is not a usable artifact.
#
# The 3D model pack (kicad-packages3d, ~6 GB) is skipped by default; set
# KICAD_3D=1 to install it (needed only for component models in
# `kicad-cli pcb render` — the board itself renders without it).
set -euo pipefail

PPA="kicad/kicad-10.0-releases"
PPA_URL="https://ppa.launchpadcontent.net/${PPA}/ubuntu"

HOOK_LIB="$(dirname "${BASH_SOURCE[0]}")/lib"
# shellcheck source=lib/preflight.sh
. "$HOOK_LIB/preflight.sh"
# shellcheck source=lib/toolchain.sh
. "$HOOK_LIB/toolchain.sh"

PREFIX='[kicad install]'
log() { printf '%s %s\n' "$PREFIX" "$*"; }

. /etc/os-release 2>/dev/null || true
CODENAME="${UBUNTU_CODENAME:-noble}"

# ── Fast path: a usable KiCad is already present → nothing to do. ─────────
# Note this is a version+pcbnew check, not `command -v`: the Ubuntu archive
# ships a kicad-cli that is too old for the generator, and it is on PATH in the
# stock image.
if toolchain_kicad_ready; then
    log "kicad-cli $(kicad-cli version 2>/dev/null) already installed (pcbnew OK)."
    exit 0
fi

# ── Preflight ─────────────────────────────────────────────────────────────
# Three distinct hosts, all required. The PPA serves the packages;
# add-apt-repository resolves the `ppa:` shorthand through launchpadlib, which
# talks to api.launchpad.net; and the keyserver serves the signing key the
# packages are verified against. Probing only the first two would let the
# preflight pass and then fail inside add-apt-repository — the previous
# version of this script fell back to `[trusted=yes]` when the keyserver was
# blocked, which installs unverified packages. Inside a sandbox that is
# survivable, but it is exactly the kind of quiet workaround that makes a
# container stop matching the environment it is supposed to reproduce.
if ! preflight_check "$PREFIX" \
    "ppa.launchpadcontent.net|http|${PPA_URL}/dists/${CODENAME}/InRelease|KiCad 10 packages" \
    "api.launchpad.net|http|https://api.launchpad.net/1.0/|PPA lookup by add-apt-repository (launchpadlib)" \
    "keyserver.ubuntu.com|http|https://keyserver.ubuntu.com/|PPA signing key (package verification)"; then
    preflight_report_blocked "$PREFIX" "the KiCad PCB pipeline"
    log "Everything else in hardware/kicad/ is source you can still edit; only"
    log "regenerating and rendering the board needs KiCad."
    exit 0
fi
log "PPA reachable — installing KiCad 10 for ${CODENAME}…"

export DEBIAN_FRONTEND=noninteractive

apt-get install -y -qq software-properties-common >/dev/null
add-apt-repository -y "ppa:${PPA}" >/dev/null
apt-get update -qq 2>/dev/null || true

log "installing kicad + symbol/footprint libraries (~1.5 GB)…"
PKGS="kicad kicad-symbols kicad-footprints"
[ "${KICAD_3D:-0}" = "1" ] && PKGS="$PKGS kicad-packages3d"
# shellcheck disable=SC2086
apt-get install -y -qq --no-install-recommends $PKGS >/dev/null

# Verify with the same predicate the fast path and the session summary use, so
# a partially-working install is never reported as done.
if ! toolchain_kicad_ready; then
    log "ERROR: kicad installed but is not usable (needs major >= ${KICAD_MIN_MAJOR}"
    log "and a working 'import pcbnew') — see docs/cloud-dev.md."
    exit 1
fi

log "installed: $(kicad-cli version 2>/dev/null || echo '?') (pcbnew OK)"
log "regenerate the board with hardware/kicad/generator/kicad_build.py"
