#include "splash.h"
#include "boot_status.h"
#include "ui_common.h"
#include "esp_app_desc.h"
#include "lvgl.h"
#include <stdatomic.h>
#include <stdio.h>

/* Embedded flame bitmap, generated by scripts/gen_flame_icon.py. */
LV_IMAGE_DECLARE(flame_icon);

/* ── Boot-status shared state ─────────────────────────────────────────── */

static _Atomic(const char *) s_status_msg = "Starting...";
static atomic_bool s_ready = false;

void boot_status_set(const char *msg)
{
    atomic_store(&s_status_msg, msg);
}

const char *boot_status_get(void)
{
    return atomic_load(&s_status_msg);
}

void boot_status_mark_ready(void)
{
    atomic_store(&s_ready, true);
}

bool boot_status_is_ready(void)
{
    return atomic_load(&s_ready);
}

/* ── Splash widgets ───────────────────────────────────────────────────── */

static lv_obj_t *s_root = NULL;
static lv_obj_t *s_status_label = NULL;

void splash_create(void)
{
    lv_obj_t *screen = lv_screen_active();

    s_root = lv_obj_create(screen);
    lv_obj_set_size(s_root, UI_LCD_W, UI_LCD_H);
    lv_obj_set_pos(s_root, 0, 0);
    lv_obj_set_style_bg_color(s_root, UI_SPLASH_BG, 0);
    lv_obj_set_style_bg_opa(s_root, LV_OPA_COVER, 0);
    lv_obj_clear_flag(s_root, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *flame = lv_image_create(s_root);
    lv_image_set_src(flame, &flame_icon);
    lv_obj_align(flame, LV_ALIGN_TOP_MID, 0, 60);

    lv_obj_t *wordmark = lv_label_create(s_root);
    lv_label_set_text(wordmark, "Bisque");
    lv_obj_set_style_text_font(wordmark, UI_FONT_BIG, 0);
    lv_obj_set_style_text_color(wordmark, UI_SPLASH_WORDMARK, 0);
    lv_obj_align(wordmark, LV_ALIGN_TOP_MID, 0, 132);

    lv_obj_t *subtitle = lv_label_create(s_root);
    lv_label_set_text(subtitle, "Kiln Controller");
    lv_obj_set_style_text_font(subtitle, UI_FONT_SMALL, 0);
    lv_obj_set_style_text_color(subtitle, UI_SPLASH_SUBTITLE, 0);
    lv_obj_align(subtitle, LV_ALIGN_TOP_MID, 0, 188);

    s_status_label = lv_label_create(s_root);
    lv_label_set_text(s_status_label, boot_status_get());
    lv_obj_set_style_text_font(s_status_label, UI_FONT_SMALL, 0);
    lv_obj_set_style_text_color(s_status_label, UI_SPLASH_STATUS, 0);
    lv_obj_align(s_status_label, LV_ALIGN_TOP_MID, 0, 260);

    lv_obj_t *version = lv_label_create(s_root);
    char version_buf[40];
    snprintf(version_buf, sizeof(version_buf), "v%s", esp_app_get_description()->version);
    lv_label_set_text(version, version_buf);
    lv_obj_set_style_text_font(version, UI_FONT_SMALL, 0);
    lv_obj_set_style_text_color(version, UI_SPLASH_VERSION, 0);
    lv_obj_align(version, LV_ALIGN_BOTTOM_LEFT, 12, -8);
}

void splash_set_status(const char *text)
{
    if (s_status_label && text) {
        lv_label_set_text(s_status_label, text);
        lv_obj_align(s_status_label, LV_ALIGN_TOP_MID, 0, 260);
    }
}

void splash_destroy(void)
{
    if (s_root) {
        lv_obj_delete(s_root);
        s_root = NULL;
        s_status_label = NULL;
    }
}
