#!/usr/bin/env python3
"""Rasterize the flame SVG to a 64x64 PNG with white bg, then emit
   an LVGL 9 lv_image_dsc_t C source as RGB565_SWAPPED (matches the
   panel's LV_COLOR_FORMAT_RGB565_SWAPPED setup in display_init.c)."""

import sys
from pathlib import Path
import cairosvg
from PIL import Image
import io

SVG = Path("/Users/ben/code/bisque/components/display/assets/flame_icon.svg")
PNG = Path("/Users/ben/code/bisque/components/display/assets/flame_icon.png")
C   = Path("/Users/ben/code/bisque/components/display/assets/flame_icon.c")
W = H = 64

# 1) SVG -> PNG (white background, 64x64).
png_bytes = cairosvg.svg2png(
    url=str(SVG),
    output_width=W,
    output_height=H,
    background_color="white",
)
PNG.write_bytes(png_bytes)

# 2) PNG -> RGBA pixels, composite onto white (in case the SVG had alpha).
img = Image.open(io.BytesIO(png_bytes)).convert("RGBA")
bg = Image.new("RGBA", img.size, (255, 255, 255, 255))
img = Image.alpha_composite(bg, img).convert("RGB")
assert img.size == (W, H), img.size

# 3) Pack as RGB565 with bytes in BE order (= LV_COLOR_FORMAT_RGB565_SWAPPED).
out = bytearray()
for y in range(H):
    for x in range(W):
        r, g, b = img.getpixel((x, y))
        v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        # SWAPPED: high byte first, low byte second.
        out.append((v >> 8) & 0xFF)
        out.append(v & 0xFF)

# 4) Emit C source.
def hex_rows(data, per_row=16):
    for i in range(0, len(data), per_row):
        chunk = data[i:i + per_row]
        yield "    " + ", ".join(f"0x{b:02X}" for b in chunk) + ","

c_body = "\n".join(hex_rows(out))

C.write_text(f"""\
/* AUTOGENERATED by tools/gen_flame_icon.py — do not edit by hand.
 * Source: components/display/assets/flame_icon.svg
 * Format: LV_COLOR_FORMAT_RGB565_SWAPPED, {W}x{H}px
 */
#include "lvgl.h"

#ifndef LV_ATTRIBUTE_LARGE_CONST
#define LV_ATTRIBUTE_LARGE_CONST
#endif
#ifndef LV_ATTRIBUTE_IMAGE_FLAME_ICON
#define LV_ATTRIBUTE_IMAGE_FLAME_ICON
#endif

static const LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMAGE_FLAME_ICON
uint8_t flame_icon_map[] = {{
{c_body}
}};

const lv_image_dsc_t flame_icon = {{
    .header = {{
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565_SWAPPED,
        .flags = 0,
        .w = {W},
        .h = {H},
        .stride = {W * 2},
        .reserved_2 = 0,
    }},
    .data_size = sizeof(flame_icon_map),
    .data = flame_icon_map,
}};
""")

print(f"wrote {PNG} ({len(png_bytes)} B), {C} ({len(out)} B pixel data)")
