/**
 * Cross-language API contract test (Layer 3).
 *
 * The C side (tests/host/test_api_json.c) drives each build_*_json() helper
 * with a fixture input and writes the resulting JSON to disk. This test
 * loads those fixtures and validates them against the same zod schemas the
 * mock-server parity test uses (test/contracts/responseSchemas.ts), which is
 * the contract the frontend relies on.
 *
 * If the firmware changes its response shape, either the C builder + this
 * schema both get updated in the same PR, or this test fails and the drift
 * is surfaced in CI.
 *
 * Fixtures are generated by the unit-host CI job (cmake --build … --target
 * api_fixtures) into tests/host/build/fixtures/api/. If they aren't present
 * — i.e. the test is run standalone without first building the host tests —
 * every test skips with a single informative message so the failure mode is
 * "nothing to validate", not a cascade of "ENOENT" errors.
 */
import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "fs";
import { join } from "path";
import { firingProfileSchema, settingsSchema } from "../../src/app/schemas/kiln";
import {
  autotuneStatusSchema,
  coneEntrySchema,
  firingProgressResponseSchema,
  historyRecordSchema,
  thermocoupleDiagSchema,
} from "./responseSchemas";
import { z } from "zod";

const FIXTURE_DIR = join(__dirname, "../../../tests/host/build/fixtures/api");

const fixturesPresent = existsSync(FIXTURE_DIR);

function load(name: string): unknown {
  return JSON.parse(readFileSync(join(FIXTURE_DIR, `${name}.json`), "utf8"));
}

describe.skipIf(!fixturesPresent)("firmware → frontend API contract", () => {
  it("/api/v1/status payload parses against firingProgressResponseSchema", () => {
    expect(firingProgressResponseSchema.parse(load("status"))).toBeDefined();
  });

  it("/api/v1/profiles/:id payload parses against firingProfileSchema", () => {
    expect(firingProfileSchema.parse(load("profile"))).toBeDefined();
  });

  it("/api/v1/settings payload parses against settingsSchema", () => {
    expect(settingsSchema.parse(load("settings"))).toBeDefined();
  });

  it("/api/v1/history element parses against historyRecordSchema", () => {
    expect(historyRecordSchema.parse(load("history_record"))).toBeDefined();
  });

  it("/api/v1/cone-table payload parses against coneEntrySchema[]", () => {
    expect(z.array(coneEntrySchema).parse(load("cone_table"))).toBeDefined();
  });

  it("/api/v1/autotune/status payload parses against autotuneStatusSchema", () => {
    expect(autotuneStatusSchema.parse(load("autotune_status"))).toBeDefined();
  });

  it("/api/v1/diagnostics/thermocouple payload parses against thermocoupleDiagSchema", () => {
    expect(thermocoupleDiagSchema.parse(load("thermocouple_diag"))).toBeDefined();
  });
});

describe.skipIf(fixturesPresent)("firmware → frontend API contract (skip notice)", () => {
  it("fixtures not built — run `cmake --build tests/host/build --target api_fixtures` first", () => {
    expect(fixturesPresent).toBe(false);
  });
});
