/**
 * Cross-language API contract test (Layer 3).
 *
 * The C side (tests/host/test_api_json.c) drives each build_*_json() helper
 * with a fixture input and writes the resulting JSON to disk. This test
 * loads those fixtures and validates them against the same zod schemas the
 * mock-server parity test uses (src/app/schemas/api.ts), which is the contract
 * the frontend relies on — and, since #176, the schemas the frontend's own
 * response types are inferred from.
 *
 * If the firmware changes its response shape, either the C builder + this
 * schema both get updated in the same PR, or this test fails and the drift
 * is surfaced in CI.
 *
 * Fixtures are generated by `make fixtures` (cmake --build tests/host/build
 * --target api_fixtures) into tests/host/build/fixtures/api/. Two things used
 * to pass silently here (#173):
 *
 *   1. No fixtures at all — the suite skipped, so `npm run test:run` in a
 *      fresh clone was green having validated nothing. Missing fixtures are
 *      now a failure; `BISQUE_SKIP_CONTRACTS=1` is the explicit opt-out for
 *      the rare case where running the C build is genuinely impossible.
 *   2. Stale fixtures — JSON left over from an older serializer validated
 *      fine. `make fixtures` now also writes _manifest.json with a SHA256 of
 *      every source that can change the emitted bytes (listed in
 *      tests/host/fixture_sources.txt); this test re-hashes them and fails
 *      when a digest has moved.
 */
import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "fs";
import { createHash } from "crypto";
import { join } from "path";
import { firingProfileSchema, pidGainsSchema, settingsSchema } from "../../src/app/schemas/kiln";
import {
  autotuneStatusSchema,
  coneEntrySchema,
  firingProgressResponseSchema,
  historyRecordSchema,
  pidResponseSchema,
  thermocoupleDiagSchema,
} from "../../src/app/schemas/api";
import {
  dispatch,
  CONE_TABLE as coneTableForTests,
  PID_GAIN_MIN as mockPidGainMin,
  PID_GAIN_MAX as mockPidGainMax,
  PID_DEFAULT_GAINS as mockPidDefaultGains,
} from "../../mock-server/router";
import { z } from "zod";

const REPO_ROOT = join(__dirname, "../../..");
const FIXTURE_DIR = join(REPO_ROOT, "tests/host/build/fixtures/api");
const MANIFEST_PATH = join(FIXTURE_DIR, "_manifest.json");
const SOURCE_LIST_PATH = join(REPO_ROOT, "tests/host/fixture_sources.txt");

const REQUIRED_FIXTURES = [
  "status",
  "profile",
  "settings",
  "history_record",
  "cone_table",
  "cone_fire_profiles",
  "autotune_status",
  "pid",
  "thermocouple_diag",
];

const REGENERATE = "Run `make fixtures` (or `make test-web`, which depends on it).";
const OPT_OUT =
  "Set BISQUE_SKIP_CONTRACTS=1 to skip the firmware contract suite when the C build is unavailable.";

const skipContracts = process.env.BISQUE_SKIP_CONTRACTS === "1";

function sha256(path: string): string {
  return createHash("sha256").update(readFileSync(path)).digest("hex");
}

/** Repo-relative source paths from tests/host/fixture_sources.txt. */
function readSourceList(): string[] {
  return readFileSync(SOURCE_LIST_PATH, "utf8")
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line !== "" && !line.startsWith("#"));
}

/**
 * Why the fixtures can't be trusted, or null when they can. Everything is
 * checked up front so the failure is one actionable message rather than a
 * cascade of ENOENTs from individual `load()` calls.
 */
function fixtureProblem(): string | null {
  if (!existsSync(FIXTURE_DIR)) {
    return `API fixtures not found at ${FIXTURE_DIR}. ${REGENERATE}\n${OPT_OUT}`;
  }

  const missing = REQUIRED_FIXTURES.filter(
    (name) => !existsSync(join(FIXTURE_DIR, `${name}.json`)),
  );
  if (missing.length > 0) {
    return `Incomplete API fixtures — missing ${missing.map((n) => `${n}.json`).join(", ")}. ${REGENERATE}`;
  }

  if (!existsSync(MANIFEST_PATH)) {
    return `API fixtures have no _manifest.json, so their freshness can't be verified — they predate the manifest or were written by hand. ${REGENERATE}`;
  }

  let recorded: Record<string, string>;
  try {
    const parsed = JSON.parse(readFileSync(MANIFEST_PATH, "utf8")) as {
      sources?: Record<string, string>;
    };
    if (!parsed.sources || typeof parsed.sources !== "object") {
      return `Malformed fixture manifest at ${MANIFEST_PATH} (no "sources" object). ${REGENERATE}`;
    }
    recorded = parsed.sources;
  } catch (err) {
    return `Unreadable fixture manifest at ${MANIFEST_PATH}: ${String(err)}. ${REGENERATE}`;
  }

  const listed = readSourceList();
  const drifted: string[] = [];
  for (const rel of listed) {
    const abs = join(REPO_ROOT, rel);
    if (!existsSync(abs)) {
      return `${rel} is listed in tests/host/fixture_sources.txt but does not exist. Update that list if the file moved or was removed.`;
    }
    if (recorded[rel] === undefined) {
      drifted.push(`${rel} (not covered by the manifest — the source list grew since generation)`);
    } else if (recorded[rel] !== sha256(abs)) {
      drifted.push(`${rel} (changed since generation)`);
    }
  }

  /**
   * A key the manifest has but the list no longer does means the manifest was
   * built from a different source list, so nothing it records can be trusted.
   * Without this, dropping an entry from fixture_sources.txt — exactly what the
   * "does not exist" path above tells you to do when a source is removed — would
   * make stale fixtures look current: the removed file stops being hashed and
   * every surviving digest still matches.
   */
  for (const rel of Object.keys(recorded)) {
    if (!listed.includes(rel)) {
      drifted.push(
        `${rel} (recorded in the manifest but no longer listed — the source list shrank since generation)`,
      );
    }
  }

  if (drifted.length > 0) {
    return `API fixtures are stale — the firmware serializers moved after they were generated:\n  ${drifted.join("\n  ")}\n${REGENERATE}`;
  }

  return null;
}

const problem = skipContracts ? null : fixtureProblem();
const fixturesUsable = !skipContracts && problem === null;

function load(name: string): unknown {
  return JSON.parse(readFileSync(join(FIXTURE_DIR, `${name}.json`), "utf8"));
}

describe.runIf(skipContracts)("firmware → frontend API contract (opted out)", () => {
  it("is skipped because BISQUE_SKIP_CONTRACTS=1", () => {
    expect(skipContracts).toBe(true);
  });
});

/**
 * Absent or stale fixtures are a hard failure, not a skip: a green
 * `npm run test:run` must mean the firmware contract was actually exercised.
 */
describe.runIf(!skipContracts && problem !== null)(
  "firmware → frontend API contract (unusable fixtures)",
  () => {
    it("fixtures are present and match the current firmware sources", () => {
      throw new Error(problem ?? "unknown fixture problem");
    });
  },
);

describe.runIf(fixturesUsable)("firmware → frontend API contract", () => {
  it("/api/v1/status payload parses against firingProgressResponseSchema", () => {
    expect(firingProgressResponseSchema.parse(load("status"))).toBeDefined();
  });

  it("/api/v1/profiles/:id payload parses against firingProfileSchema", () => {
    expect(firingProfileSchema.parse(load("profile"))).toBeDefined();
  });

  it("/api/v1/settings payload parses against settingsSchema", () => {
    expect(settingsSchema.parse(load("settings"))).toBeDefined();
  });

  it("/api/v1/history element parses against historyRecordSchema", () => {
    expect(historyRecordSchema.parse(load("history_record"))).toBeDefined();
  });

  it("/api/v1/cone-table payload parses against coneEntrySchema[]", () => {
    expect(z.array(coneEntrySchema).parse(load("cone_table"))).toBeDefined();
  });

  it("/api/v1/autotune/status payload parses against autotuneStatusSchema", () => {
    expect(autotuneStatusSchema.parse(load("autotune_status"))).toBeDefined();
  });

  it("/api/v1/pid payload parses against pidResponseSchema", () => {
    expect(pidResponseSchema.parse(load("pid"))).toBeDefined();
  });

  /**
   * The gains a manual edit can enter have to be gains the firmware accepts, so
   * the form's own rules (schemas/kiln.ts) are checked against the bounds the
   * firmware publishes rather than against a mirrored copy of them (#182).
   */
  it("firmware PID defaults and limits satisfy the client-side gain schema", () => {
    const pid = pidResponseSchema.parse(load("pid"));
    expect(pidGainsSchema.parse(pid.defaults)).toBeDefined();
    expect(
      pidGainsSchema.parse({ kp: pid.limits.max, ki: pid.limits.max, kd: pid.limits.max }),
    ).toBeDefined();
    expect(pid.limits.min).toBe(0);
  });

  /**
   * Same failure mode the cone table had, in miniature: both PID suites were
   * schema-only, so the mock could publish a different range or different
   * defaults from the firmware and every test stayed green — leaving the demo
   * validating against bounds the device rejects, or offering "restore
   * defaults" gains it never shipped. This is a value-level comparison, so the
   * mock constants and app_config.h's APP_PID_*_DEFAULT must move together.
   */
  it("mock-server PID limits and defaults match the firmware fixture exactly", () => {
    const pid = pidResponseSchema.parse(load("pid"));

    // Compared as float32, not as doubles. The firmware's gains are C floats,
    // so APP_PID_KI_DEFAULT (0.01f) reaches JSON as 0.00999999977648258 and a
    // literal 0.01 in the mock is a different double while being the identical
    // number on the device. Math.fround collapses both to the value the kiln
    // actually holds, so this still fails on any real change to a default.
    const f32 = (o: Record<string, number>) =>
      Object.fromEntries(Object.entries(o).map(([k, v]) => [k, Math.fround(v)]));

    expect(f32({ min: mockPidGainMin, max: mockPidGainMax })).toEqual(f32(pid.limits));
    expect(f32(mockPidDefaultGains)).toEqual(f32(pid.defaults));
  });

  it("/api/v1/diagnostics/thermocouple payload parses against thermocoupleDiagSchema", () => {
    expect(thermocoupleDiagSchema.parse(load("thermocouple_diag"))).toBeDefined();
  });

  /**
   * Shape validation alone let the mock's cone table drift a long way from the
   * firmware's: 36 entries instead of 37 (cone 05.5 missing, shifting every id
   * from 17 up) and roughly 20 wrong temperatures — cone 019 read
   * {630, 643, 673} against the firmware's {656, 671, 678}. The public GitHub
   * Pages demo served that as real cone data with nothing in CI to catch it.
   *
   * This is a value-level comparison, so the mock and the C table must now stay
   * byte-identical (#166).
   */
  it("mock-server cone table matches the firmware fixture exactly", () => {
    expect(coneTableForTests).toEqual(load("cone_table"));
  });

  /**
   * The same drift one level up: the mock does not call cone_fire_generate(),
   * it reimplements it, and its final ramp rates had slipped to {60, 100, 150}
   * against the firmware's {60, 150, 300}. The demo therefore generated a
   * schedule the device would never fire, and once profiles began naming a
   * nearest cone (#179) a "fast" cone 6 was labelled cone 7.
   *
   * Wording is deliberately not compared — the demo is free to name its
   * segments differently — but the schedule is the physics, so ramp rates,
   * targets, holds and the peak must match.
   */
  it("mock-server cone-fire schedule matches the firmware fixture", () => {
    const fixtures = z.array(firingProfileSchema).parse(load("cone_fire_profiles"));
    const coneSix = coneTableForTests.find((c) => c.name === "6");
    expect(coneSix).toBeDefined();

    const schedule = (p: z.infer<typeof firingProfileSchema>) => ({
      maxTemp: p.maxTemp,
      segments: p.segments.map((s) => ({
        rampRate: s.rampRate,
        targetTemp: s.targetTemp,
        holdTime: s.holdTime,
      })),
    });

    fixtures.forEach((expected, speed) => {
      const generated = dispatch("POST", "/profiles/cone-fire", {
        coneId: coneSix!.id,
        speed,
        preheat: true,
        slowCool: true,
        save: false,
      });
      expect(generated.status).toBe(200);
      const actual = firingProfileSchema.parse(generated.json);
      expect(schedule(actual)).toEqual(schedule(expected));
      // The firmware truncates its minute estimate where the mock rounds.
      expect(Math.abs(actual.estimatedDuration - expected.estimatedDuration)).toBeLessThanOrEqual(
        1,
      );
    });
  });
});
