/**
 * Cross-language API contract test (Layer 3).
 *
 * The C side (tests/host/test_api_json.c) drives each build_*_json() helper
 * with a fixture input and writes the resulting JSON to disk. This test
 * loads those fixtures and validates them against the same zod schemas the
 * mock-server parity test uses (test/contracts/responseSchemas.ts), which is
 * the contract the frontend relies on.
 *
 * If the firmware changes its response shape, either the C builder + this
 * schema both get updated in the same PR, or this test fails and the drift
 * is surfaced in CI.
 *
 * Fixtures are generated by `make fixtures` (cmake --build tests/host/build
 * --target api_fixtures) into tests/host/build/fixtures/api/. Two things used
 * to pass silently here (#173):
 *
 *   1. No fixtures at all — the suite skipped, so `npm run test:run` in a
 *      fresh clone was green having validated nothing. Missing fixtures are
 *      now a failure; `BISQUE_SKIP_CONTRACTS=1` is the explicit opt-out for
 *      the rare case where running the C build is genuinely impossible.
 *   2. Stale fixtures — JSON left over from an older serializer validated
 *      fine. `make fixtures` now also writes _manifest.json with a SHA256 of
 *      every source that can change the emitted bytes (listed in
 *      tests/host/fixture_sources.txt); this test re-hashes them and fails
 *      when a digest has moved.
 */
import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "fs";
import { createHash } from "crypto";
import { join } from "path";
import { firingProfileSchema, settingsSchema } from "../../src/app/schemas/kiln";
import {
  autotuneStatusSchema,
  coneEntrySchema,
  firingProgressResponseSchema,
  historyRecordSchema,
  thermocoupleDiagSchema,
} from "./responseSchemas";
import { CONE_TABLE as coneTableForTests } from "../../mock-server/router";
import { z } from "zod";

const REPO_ROOT = join(__dirname, "../../..");
const FIXTURE_DIR = join(REPO_ROOT, "tests/host/build/fixtures/api");
const MANIFEST_PATH = join(FIXTURE_DIR, "_manifest.json");
const SOURCE_LIST_PATH = join(REPO_ROOT, "tests/host/fixture_sources.txt");

const REQUIRED_FIXTURES = [
  "status",
  "profile",
  "settings",
  "history_record",
  "cone_table",
  "autotune_status",
  "thermocouple_diag",
];

const REGENERATE = "Run `make fixtures` (or `make test-web`, which depends on it).";
const OPT_OUT =
  "Set BISQUE_SKIP_CONTRACTS=1 to skip the firmware contract suite when the C build is unavailable.";

const skipContracts = process.env.BISQUE_SKIP_CONTRACTS === "1";

function sha256(path: string): string {
  return createHash("sha256").update(readFileSync(path)).digest("hex");
}

/** Repo-relative source paths from tests/host/fixture_sources.txt. */
function readSourceList(): string[] {
  return readFileSync(SOURCE_LIST_PATH, "utf8")
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line !== "" && !line.startsWith("#"));
}

/**
 * Why the fixtures can't be trusted, or null when they can. Everything is
 * checked up front so the failure is one actionable message rather than a
 * cascade of ENOENTs from individual `load()` calls.
 */
function fixtureProblem(): string | null {
  if (!existsSync(FIXTURE_DIR)) {
    return `API fixtures not found at ${FIXTURE_DIR}. ${REGENERATE}\n${OPT_OUT}`;
  }

  const missing = REQUIRED_FIXTURES.filter(
    (name) => !existsSync(join(FIXTURE_DIR, `${name}.json`)),
  );
  if (missing.length > 0) {
    return `Incomplete API fixtures — missing ${missing.map((n) => `${n}.json`).join(", ")}. ${REGENERATE}`;
  }

  if (!existsSync(MANIFEST_PATH)) {
    return `API fixtures have no _manifest.json, so their freshness can't be verified — they predate the manifest or were written by hand. ${REGENERATE}`;
  }

  let recorded: Record<string, string>;
  try {
    const parsed = JSON.parse(readFileSync(MANIFEST_PATH, "utf8")) as {
      sources?: Record<string, string>;
    };
    if (!parsed.sources || typeof parsed.sources !== "object") {
      return `Malformed fixture manifest at ${MANIFEST_PATH} (no "sources" object). ${REGENERATE}`;
    }
    recorded = parsed.sources;
  } catch (err) {
    return `Unreadable fixture manifest at ${MANIFEST_PATH}: ${String(err)}. ${REGENERATE}`;
  }

  const drifted: string[] = [];
  for (const rel of readSourceList()) {
    const abs = join(REPO_ROOT, rel);
    if (!existsSync(abs)) {
      return `${rel} is listed in tests/host/fixture_sources.txt but does not exist. Update that list if the file moved or was removed.`;
    }
    if (recorded[rel] === undefined) {
      drifted.push(`${rel} (not covered by the manifest — the source list grew since generation)`);
    } else if (recorded[rel] !== sha256(abs)) {
      drifted.push(`${rel} (changed since generation)`);
    }
  }

  if (drifted.length > 0) {
    return `API fixtures are stale — the firmware serializers moved after they were generated:\n  ${drifted.join("\n  ")}\n${REGENERATE}`;
  }

  return null;
}

const problem = skipContracts ? null : fixtureProblem();
const fixturesUsable = !skipContracts && problem === null;

function load(name: string): unknown {
  return JSON.parse(readFileSync(join(FIXTURE_DIR, `${name}.json`), "utf8"));
}

describe.runIf(skipContracts)("firmware → frontend API contract (opted out)", () => {
  it("is skipped because BISQUE_SKIP_CONTRACTS=1", () => {
    expect(skipContracts).toBe(true);
  });
});

/**
 * Absent or stale fixtures are a hard failure, not a skip: a green
 * `npm run test:run` must mean the firmware contract was actually exercised.
 */
describe.runIf(!skipContracts && problem !== null)(
  "firmware → frontend API contract (unusable fixtures)",
  () => {
    it("fixtures are present and match the current firmware sources", () => {
      throw new Error(problem ?? "unknown fixture problem");
    });
  },
);

describe.runIf(fixturesUsable)("firmware → frontend API contract", () => {
  it("/api/v1/status payload parses against firingProgressResponseSchema", () => {
    expect(firingProgressResponseSchema.parse(load("status"))).toBeDefined();
  });

  it("/api/v1/profiles/:id payload parses against firingProfileSchema", () => {
    expect(firingProfileSchema.parse(load("profile"))).toBeDefined();
  });

  it("/api/v1/settings payload parses against settingsSchema", () => {
    expect(settingsSchema.parse(load("settings"))).toBeDefined();
  });

  it("/api/v1/history element parses against historyRecordSchema", () => {
    expect(historyRecordSchema.parse(load("history_record"))).toBeDefined();
  });

  it("/api/v1/cone-table payload parses against coneEntrySchema[]", () => {
    expect(z.array(coneEntrySchema).parse(load("cone_table"))).toBeDefined();
  });

  it("/api/v1/autotune/status payload parses against autotuneStatusSchema", () => {
    expect(autotuneStatusSchema.parse(load("autotune_status"))).toBeDefined();
  });

  it("/api/v1/diagnostics/thermocouple payload parses against thermocoupleDiagSchema", () => {
    expect(thermocoupleDiagSchema.parse(load("thermocouple_diag"))).toBeDefined();
  });

  /**
   * Shape validation alone let the mock's cone table drift a long way from the
   * firmware's: 36 entries instead of 37 (cone 05.5 missing, shifting every id
   * from 17 up) and roughly 20 wrong temperatures — cone 019 read
   * {630, 643, 673} against the firmware's {656, 671, 678}. The public GitHub
   * Pages demo served that as real cone data with nothing in CI to catch it.
   *
   * This is a value-level comparison, so the mock and the C table must now stay
   * byte-identical (#166).
   */
  it("mock-server cone table matches the firmware fixture exactly", () => {
    expect(coneTableForTests).toEqual(load("cone_table"));
  });
});
